; MacType Control Center independent distribution configuration.
; Authored in this repository and licensed under GPL-3.0-or-later.
[General]
AlternativeFile=ini\Default.ini

[MacType]
AutoEnable=1
AutoRun=0
LoadType=0
Use64Agent=0

[UnloadDll]
; Processes that are unsafe or do not render user-interface text.
audiodg.exe
dwm.exe
fontview.exe
MsMpEng.exe
services.exe
spoolsv.exe
