// Generated by scripts/generate-settings.mjs. Do not edit.
#pragma once

#include <array>

namespace mactype {
struct SettingDefinition { const char* id; int ordinal; bool is_float; };
inline constexpr std::array<SettingDefinition, 20> kSettings{{
    {"hinting_mode", 0, false},
    {"enable_kerning", 5, false},
    {"font_loader", 21, false},
    {"font_link", 18, false},
    {"normal_weight", 2, false},
    {"bold_weight", 3, false},
    {"italic_slant", 4, false},
    {"bolder_mode", 8, false},
    {"gamma_mode", 6, false},
    {"gamma_value", 13, true},
    {"contrast", 14, true},
    {"render_weight", 15, true},
    {"anti_alias_mode", 1, false},
    {"lcd_filter", 7, false},
    {"text_tuning", 9, false},
    {"text_tuning_r", 10, false},
    {"text_tuning_g", 11, false},
    {"text_tuning_b", 12, false},
    {"hint_small_font", 27, false},
    {"max_bitmap", 25, false},
}};
}
